= ディレクトリ構成

本節では各ファイルの役割を見ていきます。

次節以降で説明する通り、GWTプロジェクトの作成はMavenを用いますが、プラグインが事後処理を行う前提のディレクトリ構造になっています。
そのため、ここではMavenを使わずにプロジェクト雛形を作成することで、GWT本来のディレクトリ構造を確認しておきます。

== GWT SDKを用いたプロジェクト作成

ここではGWT SDKを用いて作成したプロジェクトを見ていきます。
筆者がSDKで作成したファイルをgithubに置いていますので、そちらを見ながら読み進めてください。

なお、ご自身で試したい場合は http://www.gwtproject.org/gettingstarted.html[オフィシャルサイトのGetting Started]
の通りSDKをセットアップし、 `webAppCreator` コマンドを実行してください。
ただし、実際の開発でSDK及び `webAppCreator` は一切用いませんので、ここで手を動かしても後々役に立つといったことはありません。

== ディレクトリ構成概覧

----
MyWebApp/
├── MyWebApp.launch
├── README.txt
├── build.xml
├── src
│   └── com
│       └── mycompany
│           └── mywebapp
│               ├── MyWebApp.gwt.xml // <1>
│               ├── client // <2>
│               │   ├── GreetingService.java
│               │   ├── GreetingServiceAsync.java
│               │   └── MyWebApp.java
│               ├── server // <3>
│               │   └── GreetingServiceImpl.java
│               └── shared // <4>
│                   └── FieldVerifier.java
├── test
│   └── com
│       └── mycompany
│           └── mywebapp
└── war
    ├── MyWebApp.css
    ├── MyWebApp.html
    ├── WEB-INF
    │   └── web.xml
    └── favicon.ico
----

`MyWebApp.gwt.xml`(1) はGWTプロジェクトの核となるファイルです。
このファイルにGWTコンパイル時の設定などを記述します。

また、このファイルが置いてある場所も重要です。今回の場合、ソースディレクトリ(`src`)を基点として
`com/mycompany/mywebapp/MyWebApp.gwt.xml` というパスになるわけですが、この場合、
本GWTモジュールの名前は
`com.mycompany.mywebapp.MyWebApp`
ということになります。
モジュール名はユニークでなければなりません。
