= 本書の目的とカバーする範囲

本書はGWTを学ぶ際の導入となることを目的としています。
よくオープンソースのプロダクトのオンラインドキュメントにある _Getting Start_ や _Tutorial_ といった章に書かれている内容を想像してもらえればよいかと思います。

では本書を読まずともGWTオンラインドキュメントの該当箇所を読めば良いのでは、と思われるでしょう。
しかしその場合次のような問題に対面することになります。

* 和訳されたドキュメントが存在しない
* 最新バージョンに適応したドキュメントが存在しない
** 記述された手順が陳腐化しており正しく実行できない
** より適切な手順があるにもかかわらず劣った手順を学んでしまう

要するに、オフィシャルドキュメントは英語であり、たとえそれを許容できたとしても内容が古いので学習効率が非常に悪いのです。

このような状況を解消し、初学者が正しい手続きで効率的にGWTを用いた開発を行えるようにすることが本書の目的です。

= 対象読者

日常Javaを用いて開発をしており、これからGWTを学びたいと考えている人を想定しています。

= 実行環境と前提

本書では次に示す環境を前提として説明を行っていきます。
これらに関してはインストールや初期セットアップ方法、基礎的な使用方法などについて本書では触れません。

必ずしも同じ環境を揃える必要はなく、代替環境を用いても問題は無いはずですが、その場合は適宜読み替えて頂く必要があります。

* Ubuntu 16.04 LTS
** WindowsやMacでも問題ありませんが、コマンド実行はbashを前提に記載しています。
** 筆者がWindowsで開発する場合は、 http://gitforwindows.org/[Git for Windows] 付属の git bash を用いています。
* http://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle JDK9] 9.0.1
** GWT2.8.2よりJDK9上で開発ができるようになりましたのでこれを用います。
** なお、GWTが対応しているソースコード書式はJava8までです。
* https://maven.apache.org/download.cgi[Apache Maven] 3.5.2
