== 生成ファイルの概説

本節では、
link:#generate-project[{title-generate-project}]
節で生成したファイル群について見ていきます。

=== Mavenモジュール

Maven親モジュール
`gwtbookcode`
と、この下に3つのMaven子モジュール
`gwtbookcode-client`, `gwtbookcode-server`, `gwtbookcode-shared`
が生成されています。
まずはこれらMavenモジュールの役割分担について説明します。

`gwtbookcode-client`は、GWTコンパイラによってコンパイルされ、
最終的にJavaScript(等の静的リソースファイル)となるものを格納します。

`gwtbookcode-server`は、通常のJavaとしてコンパイルされるServletなどを格納します。

`gwtbookcode-shared`は、クライアントとサーバ両方で利用するものを格納します。
GWTコンパイラによってJavaScriptにも変換されますし、Javaコンパイラによって`.class`ファイルも生成されます。

続いて各Mavenモジュール内の主要ファイルを見ていきます。

=== `gwtbookcode-client`

==== ファイル構成

----
gwtbookcode-client
├── pom.xml
└── src
    └── main
        ├── java
        │   └── com
        │       └── github
        │           └── yukihane
        │               └── gwtbook
        │                   └── App.java
        └── module.gwt.xml
----

==== `App.java`

コードの一部を抜粋します。
----
package com.github.yukihane.gwtbook;

import com.google.gwt.core.client.EntryPoint;

public class App implements EntryPoint {

  public void onModuleLoad() {
    // ...
  }
}
----

前述の通り `gwtbookcode-client` 内のコードはJavaScriptに変換されます。
`EntryPoint` を実装したクラスは名前の通りエントリーポイントであり、
`onModuleLoad` が一番最初に呼ばれるメソッドです(`main` メソッドのようなものです)。


==== `module.gwt.xml`

`module.gwt.xml`はGWTモジュールの定義を記述するもので、GWTにおいて核となるファイルです。
自動生成されたファイルを次に示します。

----
<?xml version="1.0" encoding="UTF-8"?>
<module>
  <inherits name="com.google.gwt.user.User" /> // <1>
  <inherits name="com.google.gwt.user.theme.clean.Clean" />

  <source path="" /> // <2>

  <entry-point class="com.github.yukihane.gwtbook.App" /> // <3>

  <!-- Only support recent browsers -->
  <set-property name="user.agent" value="ie10,gecko1_8,safari" /> // <4>
</module>
----
<1> 利用するGWTモジュールを記述します。
Mavenでいうところの `dependency` のようなものです。
<2> GWTコンパイル対象とするソースのパス。
`gwtbookcode-client/pom.xml` で設定している
`moduleName` のパッケージに対応するソースディレクトリからの相対パスになります。
今回の場合、 `moduleName` は `com.github.yukihane.gwtbook.App` 、
そしてこのファイルで指定している `source path` は空ですので
`com/github/yukihane/gwtbook` 以下がGWTコンパイル対象ということになります。
<3> エントリーポイント。
<4> コンパイルオプション的なものもあればここで設定します。
ここで設定している `user.agent` は、対応するブラウザを決める属性です
footnote:[GWTはブラウザの種類ごとに、そのブラウザに適したJavaScriptコードを生成します。
その他、多言語対応では言語ごとにコードを生成したりもします。]。

[NOTE]
本書では_Mavenモジュール_と_GWTモジュール_が登場します。
これらはそれぞれ異なるものを指している用語なので混同しないように注意してください。 +
`pom.xml`によって定義されているものが_Mavenモジュール_、
`*.gwt.xml`によって定義されているものが_GWTモジュール_です。

[TIP]
*「モジュール」とは？* +
簡単に言うと、何らかの役割ごとに寄せ集めてひとかたまりにしたもの、でしょうか。
Javaで言えば、最終的には1モジュールごとに1つの`jar`として出力される、といったイメージの単位です
(あくまでイメージ。そうでないことも多々あります)。 +
ちなみに、GWTモジュールについてもう少し正確に知りたいのであれば公式サイトの
*FAQ - Client*のページfootnote:[http://www.gwtproject.org/doc/latest/FAQ_Client.html#What_is_a_GWT_Module?]に説明があります。


=== `gwtbookcode-server`

==== ファイル構成

`gwtbookcode-server` の構成は典型的な(GWTとは無関係な) `WAR` モジュールです。
----
gwtbookcode-server
├── pom.xml
└── src
    └── main
        ├── java
        │   └── com
        │       └── github
        │           └── yukihane
        │               └── gwtbook
        │                   └── GreetingServiceImpl.java
        ├── tomcatconf
        │   └── context.xml
        └── webapp
            ├── WEB-INF
            │   └── web.xml
            ├── favicon.ico
            ├── gwtbookcode.css
            └── index.html
----

==== `GreetingServiceImpl.java`

----
package com.github.yukihane.gwtbook;

import com.google.gwt.user.server.rpc.RemoteServiceServlet;

public class GreetingServiceImpl extends RemoteServiceServlet implements GreetingService {

  public GreetingResponse greetServer(String input) throws IllegalArgumentException {
  ...
  }
}
----

GWT-RPCを処理するServletクラスです。
`HttpServlet` を直接継承するのではなく
`RemoteServiceServlet` を継承しています(なお `RemoteServiceServlet` が
`HttpServlet` を継承しています)。

実装対象の　`GreetingService` インタフェースは次に説明する
`gwtbookcode-shared` モジュールにあります。

=== `gwtbookcode-shared`

==== ファイル構成

----
gwtbookcode-shared
├── pom.xml
└── src
    └── main
        └── java
            └── com
                └── github
                    └── yukihane
                        └── gwtbook
                            ├── FieldVerifier.java
                            ├── GreetingResponse.java
                            ├── GreetingService.java
                            └── GreetingServiceAsync.java
----

`FieldVerifier.java` はクライアントとサーバ両方で用いるビジネスロジック実装クラス、
`GreetingResponse.java` はクライアントとサーバ間でやり取りを行うためのデータクラス(いわゆるDTO)、
`GreetingService.java` 及び `GreetingServiceAsync.java` はGWT-RPCに関わるものです。
GWT-RPCについては後の章で解説します。
