= はじめに

== 本書の目的とカバーする範囲

本書はGWT(バージョン2.7以降; 本書ではバージョン2.8.2を用います)を学ぶ際の導入となることを目的としています。
よくオープンソースのプロダクトのオンラインドキュメントにある _Getting Started_ や _Tutorial_ といった章に書かれている内容を想像してもらえればよいかと思います。

では本書を読まずともGWTオンラインドキュメントの該当箇所を読めば良いのでは、と思われるでしょう。
しかしその場合次のような問題に直面することになります。

* 和訳されたドキュメントが存在しない
* 最新バージョンに適応したドキュメントが存在しない
** 記述された手順が陳腐化しており正しく実行できない
** より適切な手順があるにもかかわらず劣った手順を学んでしまう

要するに、オフィシャルドキュメントは英語であり、更に内容がアップデートされていないため学習効率が非常に悪いのです。
入門段階では読者自身でどこが正しくどこが陳腐化した記述なのか判断できないので致命的な問題といえます。

このような状況を解消し、初学者が正しい手続きで効率的にGWTを用いた開発を行えるようにすることが本書の目的です。

参考までに、もはや役に立たないGWTに関する記述の目安となるチェックリストを以下に示します。
このリストに1つでも当てはまるような文章を読むよりは、本書を読んだ方が現状に即したGWTへの理解が得られると確信しています。

* *GWT2.5未満のバージョンを対象にしている*
** SuperDevModeという動作モードが(試験的に)導入されたバージョンが2.5で、これは従来のDevModeとは操作方法がかなり異なります。
** 正規期導入は2.7なので、できれば2.7以降の解説が望ましいです。
* *2012年以前に執筆/出版された文章/書籍である*
** GWT2.5がリリースされたのが2012年10月であるため。
** 2013年1月出版の
https://www.manning.com/books/gwt-in-action-second-edition[GWT in Action, Second Edition]
はGWT2.4ベースでGWT2.5にも少し言及がありますが、解説は古いものでした。
** 筆者が確認した限り、日本語で書かれたGWTに関する書籍は全てこの条件に当てはまります。英語書籍ですらほぼ全滅でしょう。
* *Webブラウザへのプラグインインストールを要求する記述がある*
** 過去のバージョンでデバッグ時に使用していたものですが、もはやいずれのWebブラウザでも本プラグインは動作しません。
* *開発に関する作業の大半をEclipseのメニューを選択することで実施している*
** 以前Googleが提供していたEclipseプラグインは上記のWebブラウザプラグインを前提としているものなので利用できません。
** 実際には、現行バージョンGWT向けプラグインも開発されています footnote:[http://gwt-plugins.github.io/documentation/[GWT Eclipse Plugin]]が、こちらのプラグインベースで書かれた解説はまだまれだと思います。
* *JSNIの説明はあるがJsInteropの説明がない*
** JavaScriptとの相互連携の仕組みですが、旧方式であるJSNIは後継のJsInteropに取って代わられつつあります。

== 対象読者

日常Javaを用いて開発をしており、これからGWTを学びたいと考えている人を想定しています。

== 実行環境と前提

本書では次に示す環境を前提として説明を行っていきます。
これらに関してはインストールや初期セットアップ方法、基礎的な使用方法などについて本書では触れません。

必ずしも同じ環境を揃える必要はなく、代替環境を用いても問題は無いはずですが、その場合は適宜読み替えて頂く必要があります。

* *Ubuntu 16.04 LTS*
** WindowsやMacでも問題ありませんが、コマンド実行はbashを前提に記載しています。
** 筆者がWindowsで開発する場合は、 http://gitforwindows.org/[Git for Windows] 付属の git bash を用いています。
* *Chromium または Google Chrome*
** 本書では当ブラウザのDevToolsを前提に説明を行います。
* *http://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle JDK9] 9.0.1*
** GWT開発には1.8以降が必要ですfootnote:[link:http://www.gwtproject.org/gettingstarted.html#prereqs[公式サイト]
にある正確な記述は次の通りです:
You will need the Java SDK version 1.8 or later (Note that 1.7 is supported
to compile and run sources, but may not work correctly in dev mode).]。
GWT2.8.2よりJDK9上でもコンパイルできるようになりましたのでこれを用います。
** なお、GWTが対応しているソースコード書式はJava8までです。
* *https://maven.apache.org/download.cgi[Apache Maven] 3.5.2*
* *https://tomcat.apache.org/download-80.cgi[Apache Tomcat] 8.5.24*
** 本書の説明上、Servlet3.0(以降)を実行可能なWebサーバが必要です。

[TIP]
勘違いされることが多いですが、GWTの実行にServletコンテナ(JavaEEアプリケーションサーバ)が必須、というわけではありません。
Servletを利用した便利機能(GWT-RPC)をGWTが持っているのですが、
それを使用しないのであればNginx上で動作させたりRailsアプリに組み込んだりすることも可能です。 +
コンパイル後のクライアントサイドGWTは単なるJavaScript(等の静的リソース)です。

また、Mavenがどのような目的で使われるソフトウェアか知っており、自身で実行してみたことがある、
という程度のスキルを有することを前提としています。

== 本書のながれ

<<hello-gwt#test,Activity overview>>

link:hello-gwt.xhtml#test[{title-hello-gwt}]章ではサンプルGWTプロジェクトを作成し実行する手順を確認していきます。
また、その過程で作成するファイルの役割についても見ていきます。


link:#classical-app-dev[{title-classical-app-dev}]章では、過去推奨されていた方法を用いて簡単なアプリケーションを作成します。
ここで「過去推奨されていた方法」というのは、GWT独自のテクノロジを用いた開発のことです。
本章で説明する内容は実際の開発で役立つことは少ないですが、現在及びこれから行うべき開発方法と対比する上で参考になるはずです。

== サンプルコードについて

https://github.com/yukihane/gwtbookcode にサンプルコードを置いています。
